name: 'Export all secrets to env variables'
description: 'Utility action that exports all github secrets to environment variables'
author: 'Jose Pereira @oNaiPs & Tamas Kadar @KTamas'
inputs:
  secrets:
    required: true
    description: JSON representation of the secrets, use provided placeholder'
  prefix:
    required: false
    description: 'Prefix to add to all secrets, e.g.: SECRET_'
  include:
    required: false
    description: 'Comma-separated list of secrets to export'
  exclude:
    required: false
    description: 'Comma-separated list of secrets to skip exporting'
  convert:
    required: false
    description: 'Converts secrets name to a specific string format'
  starts_with:
    required: false
    description: 'Only export secrets that start with the provided string'
  convert_prefix:
    required: false
    description: 'If used with starts_with, only convert the non-matching part of the secret name'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: book-open
  color: orange
